In [2]:
import torch

x = torch.tensor([1,2,3], dtype=torch.float, requires_grad = True)
print(x)

y = x+2
print(y)

z = y*y*2
print(z)

loss = torch.tensor([18, 1.0, 0.001])
z.backward(loss)

print(x.grad)

tensor([1., 2., 3.], requires_grad=True)
tensor([3., 4., 5.], grad_fn=<AddBackward0>)
tensor([18., 32., 50.], grad_fn=<MulBackward0>)
tensor([2.1600e+02, 1.6000e+01, 2.0000e-02])


In [3]:
#3 ways to stop having grad_func

x = torch.randn(3, requires_grad = True)
print(x)

#1st Way
#x.requires_grad_(False)
#x.requires_grad = False
#print(x)

#2nd way
z=x.detach_()
print(z)


#3rd way
with torch.no_grad():
    y = x + 2
    print(y)


tensor([-0.0741, -0.4923, -0.1474], requires_grad=True)
tensor([-0.0741, -0.4923, -0.1474])
tensor([1.9259, 1.5077, 1.8526])


In [4]:
weigths = torch.ones(4, requires_grad = True)

for epoch in range(3):
    model_output = (weigths*3).sum()
    model_output.backward()
    print(weigths.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])
