In [20]:
import torch
x = torch.tensor([4, 2, 3])
x.dtype
x.size()


y= torch.tensor([1.5, 2.4, 7.8])
y

torch.add(x,
y.sub_(x)   #in-place operation
z = y.sub(x)  #not in place
z

tensor([-6.5000, -1.6000,  1.8000])

In [30]:
x = torch.rand(5,3)
print(x)
print(x[:, 1])

print(x[1,1])
print(x[1,1].item())

y = x.view(15)
print(y)


y = x.view(-1,5)
y

tensor([[0.1065, 0.1727, 0.8614],
        [0.7570, 0.7284, 0.6112],
        [0.6590, 0.3285, 0.5315],
        [0.2453, 0.0541, 0.3495],
        [0.0968, 0.2969, 0.7662]])
tensor([0.1727, 0.7284, 0.3285, 0.0541, 0.2969])
tensor(0.7284)
0.7284080982208252
tensor([0.1065, 0.1727, 0.8614, 0.7570, 0.7284, 0.6112, 0.6590, 0.3285, 0.5315,
        0.2453, 0.0541, 0.3495, 0.0968, 0.2969, 0.7662])


tensor([[0.1065, 0.1727, 0.8614, 0.7570, 0.7284],
        [0.6112, 0.6590, 0.3285, 0.5315, 0.2453],
        [0.0541, 0.3495, 0.0968, 0.2969, 0.7662]])

In [37]:
import numpy as np

a = torch.ones(5)
b = a.numpy()
print(type(b))


a.add_(1)
print(a)
print(b)

<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [39]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [41]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to('cpu')

In [43]:
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)